Repository popcorndao/workspace, pull requests merged in 2021-11, with the labels that each got.

#687 removes set token vendor files in favor of direct import from npm, up…
  packages/app/components/Proposals/CurrentStandings.tsx
  packages/contracts/adapters/GrantElection/GrantElectionAdapter.ts
  packages/contracts/adapters/HYSIBatchInteraction/HYSIBatchInteractionAdapter.ts
  packages/contracts/contracts/externals/interfaces/SetToken.sol
  packages/contracts/hardhat.config.ts
  packages/contracts/lib/SetToken/BasicIssuanceModuleManager.ts
  packages/contracts/lib/SetToken/Configuration.ts
  packages/contracts/lib/SetToken/SetTokenCreator.ts
  packages/contracts/lib/SetToken/StreamingFeeModuleManager.ts
  packages/contracts/lib/SetToken/vendor/set-protocol/artifacts/BasicIssuanceModule.json
  packages/contracts/lib/SetToken/vendor/set-protocol/artifacts/SetToken.json
  packages/contracts/lib/SetToken/vendor/set-protocol/artifacts/SetTokenCreator.json
  packages/contracts/lib/SetToken/vendor/set-protocol/artifacts/StreamingFeeModule.json
  packages/contracts/lib/SetToken/vendor/set-protocol/types/BasicIssuanceModule.d.ts
  packages/contracts/lib/SetToken/vendor/set-protocol/types/BasicIssuanceModuleFactory.ts
  packages/contracts/lib/SetToken/vendor/set-protocol/types/SetToken.d.ts
  packages/contracts/lib/SetToken/vendor/set-protocol/types/SetTokenCreator.d.ts
  packages/contracts/lib/SetToken/vendor/set-protocol/types/SetTokenCreatorFactory.ts
  packages/contracts/lib/SetToken/vendor/set-protocol/types/SetTokenFactory.ts
  packages/contracts/lib/SetToken/vendor/set-protocol/types/StreamingFeeModule.d.ts
  packages/contracts/lib/SetToken/vendor/set-protocol/types/StreamingFeeModuleFactory.ts
  packages/contracts/package.json
  packages/contracts/scripts/finalizeElection.ts
  packages/contracts/test/BeneficiaryVaults.test.ts
  packages/contracts/test/GrantElections.test.ts
  packages/contracts/test/HysiBatchInteraction.test.ts
  packages/contracts/test/RewardsEscrow.test.ts
  packages/contracts/test/Staking.test.ts
  packages/contracts/test/fork/HysiBatchInteraction.test.ts
  packages/contracts/test/fork/HysiBatchZapper.test.ts
  yarn.lock
Labels: SmartContracts, Components

#662 LinkedIn conversion set on the 'Join Waitlist' button on the landing page
  packages/app/components/LinkedInPixel.tsx
  packages/app/pages/index.tsx
Labels: TheKettle

#717 Add 'Partners' and 'As seen in' sections to landing page
  packages/app/pages/index.tsx
  packages/app/public/images/asseenin/Investing.com.png
  packages/app/public/images/asseenin/bitcoinist.png
  packages/app/public/images/asseenin/coindesk.png
  packages/app/public/images/asseenin/dwn.png
  packages/app/public/images/asseenin/entrepreneur.png
  packages/app/public/images/asseenin/it.png
  packages/app/public/images/asseenin/magnates.png
  packages/app/public/images/asseenin/newsbtc.png
  packages/app/public/images/asseenin/potato.png
  packages/app/public/images/asseenin/sarson.png
  packages/app/public/images/asseenin/techtimes.png
  packages/app/public/images/asseenin/utoday.png
  packages/app/public/images/asseenin/yahoo.png
  packages/app/public/images/asseeninbg.svg
  packages/app/public/images/investor-partners/amino.png
  packages/app/public/images/investor-partners/bb.png
  packages/app/public/images/investor-partners/cakebox.png
  packages/app/public/images/investor-partners/cryptofounders.png
  packages/app/public/images/investor-partners/hestia.png
  packages/app/public/images/investor-partners/impossible.png
  packages/app/public/images/investor-partners/jump.png
  packages/app/public/images/investor-partners/kenetic.png
  packages/app/public/images/investor-partners/lao.png
  packages/app/public/images/investor-partners/newform.png
  packages/app/public/images/ourpartnersbg.svg
  packages/app/tailwind.config.js
Labels: frontend, TheKettle

#718 update README.md prerequisites section with additional information
  README.md
Labels: documentation

#728 typo
  packages/app/components/LinkedInPagePixel.tsx
Labels: bug, Components, TheKettle
